defaults:
  - _self_
  - data: ds_medium
  - model: vgg11_train
  - optimizer: sgd
  - override hydra/sweeper: optuna
paths:
  data: ./1_data

direction: maximize
study_name: mnist
storage: null
n_trials: 2
n_jobs: 1
sampler: tpe
seed: 123

mlflow:
  runname: "sample2"

params:
  epoch_count: 3
  lr: 5e-4
  train:
    batch_size: 12
  test:
    batch_size: 10
args:
  resume: False
  lr: 0.1

hydra:
  run:
    dir: ./outputs/${model._target_}/${now:%Y-%m-%d}/${now:%H-%M-%S}
