defaults:
  - _self_
  - data: ds_small
  - model: vgg11_train
  - optimizer: sgd
paths:
  data: ../../1_data

params:
  epoch_count: 3
  lr: 5e-4
  train:
    batch_size: 128
  test:
    batch_size: 100
args:
  resume: False
  lr: 0.1

hydra:
  run:
    dir: ./outputs/${model._target_}/${now:%Y-%m-%d}/${now:%H-%M-%S}
