defaults:
  - _self_
  - data: ds_medium
  - model: vgg11_train
  - optimizer: sgd
  - override hydra/sweeper: optuna
paths:
  data: ./1_data

mlflow:
  runname: "sample77"

params:
  epoch_count: 3
  lr: 5e-4
  train:
    batch_size: 12
  test:
    batch_size: 10
args:
  resume: False
  lr: 0.1
  offline: True

hydra:
  run:
    dir: ./outputs/${model._target_}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    direction: maximize
    study_name: sphere
    storage: null
    n_trials: 7
    n_jobs: 1



